services:
  app:
    build:
      context: .
    ports:
      - "3600:3600"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "go build cmd/shiftmanager/main.go && ./main"
    restart: always