services:
  app:
    build:
      context: .
    ports:
      - "3600:3600"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    environment:
      - ENV=local
    command: sh -c "go run cmd/shiftmanager/main.go"